version: "3.8"

services:
  node:
    image: node:18-alpine3.15
    command: tail -f /dev/null
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
  app:
    image: test
    build: 
      context: ./
      dockerfile: docker/dockerfile
    ports:
      - 3001:3000