FROM node:18-alpine3.15 as builder
WORKDIR /app
ADD ./app .
RUN rm -rf dist node_modules
RUN npm install -g @nestjs/cli
RUN npm install --production
RUN npm run build

FROM node:18-alpine3.15 as app
WORKDIR /app
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
RUN chown -R node:node /app
USER node
CMD [ "node", "dist/main.js" ]
EXPOSE 3000